fmt:
  # Use a third-party repo since the official repo doesn't include tags.
  # https://github.com/rust-lang-nursery/docker-rust-nightly/issues/3
  image: instrumentisto/rust:nightly-2020-06-04
  script:
    - cargo +nightly fmt -- --check

check:
  image: rust:1.44.0
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy --locked --all-targets --features strict

test:
  image: rust:1.44.0
  script:
    - cargo test --locked
